// This file is generated by Slice Machine. Update with care!

import Cta from './Cta';
import Faq from './Faq';
import FeaturedBlogPosts from './FeaturedBlogPosts';
import Features from './Features';
import HeroSection from './HeroSection';
import TestSlice from './TestSlice';

export {
	Cta,
	Faq,
	FeaturedBlogPosts,
	Features,
	HeroSection,
	TestSlice,
};

export const components = {
	cta: Cta,
	faq: Faq,
	featured_blog_posts: FeaturedBlogPosts,
	features: Features,
	hero_section: HeroSection,
	test_slice: TestSlice,
};
