// This file is generated by Slice Machine. Update with care!

import ArticleListContainer from './ArticleListContainer';
import Cta from './Cta';
import DropdownMenu from './DropdownMenu';
import Faq from './Faq';
import FeaturedBlogPosts from './FeaturedBlogPosts';
import FeaturedProducts from './FeaturedProducts';
import Features from './Features';
import FooterLinks from './FooterLinks';
import HeroSection from './HeroSection';
import Image from './Image';
import Reassurance from './Reassurance';
import ScrollingCards from './ScrollingCards';
import TestSlice from './TestSlice';
import Text from './Text';

export {
	ArticleListContainer,
	Cta,
	DropdownMenu,
	Faq,
	FeaturedBlogPosts,
	FeaturedProducts,
	Features,
	FooterLinks,
	HeroSection,
	Image,
	Reassurance,
	ScrollingCards,
	TestSlice,
	Text,
};

export const components = {
	article_list_container: ArticleListContainer,
	cta: Cta,
	dropdown_menu: DropdownMenu,
	faq: Faq,
	featured_blog_posts: FeaturedBlogPosts,
	featured_products: FeaturedProducts,
	features: Features,
	footer_links: FooterLinks,
	hero_section: HeroSection,
	image: Image,
	reassurance: Reassurance,
	scrolling_cards: ScrollingCards,
	test_slice: TestSlice,
	text: Text,
};
