// This file is generated by Slice Machine. Update with care!

import Cta from './Cta';
import Faq from './Faq';
import FeaturedBlogPosts from './FeaturedBlogPosts';
import Features from './Features';
import FooterLinks from './FooterLinks';
import HeroSection from './HeroSection';
import Reassurance from './Reassurance';
import TestSlice from './TestSlice';

export {
	Cta,
	Faq,
	FeaturedBlogPosts,
	Features,
	FooterLinks,
	HeroSection,
	Reassurance,
	TestSlice,
};

export const components = {
	cta: Cta,
	faq: Faq,
	featured_blog_posts: FeaturedBlogPosts,
	features: Features,
	footer_links: FooterLinks,
	hero_section: HeroSection,
	reassurance: Reassurance,
	test_slice: TestSlice,
};
